config/routes.rb
Inventory::Application.routes.draw do

#  devise_for :users
#  devise_scope :user do
#    get "signup",   :to => "accounts#new"
#    get "signin",   :to => "devise/sessions#new"
#    get "signout",  :to => "devise/sessions#destroy"
#  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  post "dynamic_devices/:id" => "patient_assignments#dynamic_devices", :as => "dynamic_devices"
  post "dynamic_patients/:id" => "patient_assignments#dynamic_patients", :as => "dynamic_patients"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "users/:id/password" => "users#password", :as => "reset_pass"
  get "reports/all_locations_summary" => "reports#all_locations_summary", :as => "all_locations_summary"
  get "reports/location_summary/:id" => "reports#location_summary", :as => "location_summary"
  get "reports/problematic_devices" => "reports#problematic_devices", :as => "problematic_devices"
  get "reports/devices_in_use" => "reports#devices_in_use", :as => "devices_in_use"
  get "device_by_location/:id" => "locations#devices_report", :as => "device_by_location"


  resources :device_batteries
  resources :device_carriers  
  resources :audits
  resources :disposable_types
  resources :disposables
  resources :devices
  resources :device_problem_statuses
  resources :device_problems
  resources :device_tests
  resources :device_types
  resources :device_statuses
  resources :groups
  resources :home
  resources :locations
  resources :location_assignments
  resources :location_types
  resources :patients
  resources :patient_assignments
  resources :practices
  resources :sessions
  resources :users do
    member do
      get 'password'
    end
  end


end

app/models/device_carrier.rb
class DeviceCarrier < ActiveRecord::Base
  validates :device_carrier, :presence => true

  has_many :device
end

app/controllers/device_carriers_controller.rb
class DeviceCarriersController < ApplicationController
  # GET /device_carriers
  # GET /device_carriers.json
  def index
    @device_carriers = DeviceCarrier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @device_carriers }
    end
  end

  # GET /device_carriers/1
  # GET /device_carriers/1.json
  def show
    @device_carrier = DeviceCarrier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device_carrier }
    end
  end

  # GET /device_carriers/new
  # GET /device_carriers/new.json
  def new
    @device_carrier = DeviceCarrier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device_carrier }
    end
  end

  # GET /device_carriers/1/edit
  def edit
    @device_carrier = DeviceCarrier.find(params[:id])
  end

  # POST /device_carriers
  # POST /device_carriers.json
  def create
    @device_carrier = DeviceCarrier.new(params[:device_carrier])

    respond_to do |format|
      if @device_carrier.save
        format.html { redirect_to @device_carrier, notice: 'Device carrier was successfully created.' }
        format.json { render json: @device_carrier, status: :created, location: @device_carrier }
      else
        format.html { render action: "new" }
        format.json { render json: @device_carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /device_carriers/1
  # PUT /device_carriers/1.json
  def update
    @device_carrier = DeviceCarrier.find(params[:id])

    respond_to do |format|
      if @device_carrier.update_attributes(params[:device_carrier])
        format.html { redirect_to @device_carrier, notice: 'Device carrier was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @device_carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_carriers/1
  # DELETE /device_carriers/1.json
  def destroy
    @device_carrier = DeviceCarrier.find(params[:id])
    @device_carrier.destroy

    respond_to do |format|
      format.html { redirect_to device_carriers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/device_carriers_helper.rb
module DeviceCarriersHelper
end

app/views/device_carriers/_form.html.erb
<%= form_for(@device_carrier) do |f| %>
  <% if @device_carrier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device_carrier.errors.count, "error") %> prohibited this device_carrier from being saved:</h2>

      <ul>
      <% @device_carrier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_carrier %><br />
    <%= f.text_field :device_carrier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/device_carriers/edit.html.erb
<h1>Editing device_carrier</h1>

<%= render 'form' %>

<%= link_to 'Show', @device_carrier %> |
<%= link_to 'Back', device_carriers_path %>

app/views/device_carriers/index.html.erb
<h1>Listing device_carriers</h1>

<table>
  <tr>
    <th>Device carrier</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @device_carriers.each do |device_carrier| %>
  <tr>
    <td><%= device_carrier.device_carrier %></td>
    <td><%= link_to 'Show', device_carrier %></td>
    <td><%= link_to 'Edit', edit_device_carrier_path(device_carrier) %></td>
    <td><%= link_to 'Destroy', device_carrier, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device carrier', new_device_carrier_path %>

app/views/device_carriers/new.html.erb
<h1>New device_carrier</h1>

<%= render 'form' %>

<%= link_to 'Back', device_carriers_path %>

app/views/device_carriers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Device carrier:</b>
  <%= @device_carrier.device_carrier %>
</p>


<%= link_to 'Edit', edit_device_carrier_path(@device_carrier) %> |
<%= link_to 'Back', device_carriers_path %>