config/routes.rb
Inventory::Application.routes.draw do

#  devise_for :users
#  devise_scope :user do
#    get "signup",   :to => "accounts#new"
#    get "signin",   :to => "devise/sessions#new"
#    get "signout",  :to => "devise/sessions#destroy"
#  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  post "dynamic_devices/:id" => "patient_assignments#dynamic_devices", :as => "dynamic_devices"
  post "dynamic_patients/:id" => "patient_assignments#dynamic_patients", :as => "dynamic_patients"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "users/:id/password" => "users#password", :as => "reset_pass"
  get "reports/all_locations_summary" => "reports#all_locations_summary", :as => "all_locations_summary"
  get "reports/location_summary/:id" => "reports#location_summary", :as => "location_summary"
  get "reports/problematic_devices" => "reports#problematic_devices", :as => "problematic_devices"
  get "reports/devices_in_use" => "reports#devices_in_use", :as => "devices_in_use"
  get "device_by_location/:id" => "locations#devices_report", :as => "device_by_location"


  resources :device_batteries
  resources :device_carriers  
  resources :audits
  resources :disposable_types
  resources :disposables
  resources :devices
  resources :device_problem_statuses
  resources :device_problems
  resources :device_tests
  resources :device_types
  resources :device_statuses
  resources :groups
  resources :home
  resources :locations
  resources :location_assignments
  resources :location_types
  resources :patients
  resources :patient_assignments
  resources :practices
  resources :sessions
  resources :users do
    member do
      get 'password'
    end
  end


end

app/models/patient_assignment.rb
class PatientAssignment < ActiveRecord::Base
  validates :device_id, :presence => true
  validates :patient_id, :presence => true

  belongs_to :patient
  belongs_to :device
end

app/controllers/patient_assignments_controller.rb
class PatientAssignmentsController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction

  # GET /patient_assignments
  # GET /patient_assignments.json
  def index
    @patient_assignments = PatientAssignment.includes(:device, :patient).order(sort_column + " " + sort_direction).page(params[:page]).per(25)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patient_assignments }
    end
  end

  # GET /patient_assignments/1
  # GET /patient_assignments/1.json
  def show
    @patient_assignment = PatientAssignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient_assignment }
    end
  end

  # GET /patient_assignments/new
  # GET /patient_assignments/new.json
  def new
    @patient_assignment = PatientAssignment.new
    @locations = Location.order("location_name ASC")
    @patients = Patient.order("last_name ASC")
    @devices = Device.order("serial_number ASC")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient_assignment }
    end
  end

  # GET /patient_assignments/1/edit
  def edit
    @patient_assignment = PatientAssignment.find(params[:id])
    @locations = Location.order("location_name ASC")
    @patients = Patient.order("last_name ASC")
    @devices = Device.order("serial_number ASC")
  end

  # POST /patient_assignments
  # POST /patient_assignments.json
  def create
    @patient_assignment = PatientAssignment.new(params[:patient_assignment])

    respond_to do |format|
      if @patient_assignment.save
        format.html { redirect_to @patient_assignment, notice: 'Patient assignment was successfully created.' }
        format.json { render json: @patient_assignment, status: :created, location: @patient_assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @patient_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patient_assignments/1
  # PUT /patient_assignments/1.json
  def update
    @patient_assignment = PatientAssignment.find(params[:id])

    respond_to do |format|
      if @patient_assignment.update_attributes(params[:patient_assignment])
        format.html { redirect_to @patient_assignment, notice: 'Patient assignment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_assignments/1
  # DELETE /patient_assignments/1.json
  def destroy
    @patient_assignment = PatientAssignment.find(params[:id])
    @patient_assignment.destroy

    respond_to do |format|
      format.html { redirect_to patient_assignments_url }
      format.json { head :ok }
    end
  end
  
  def dynamic_patients
    @location = Location.find(params[:id])
    @patients = @location.get_patients
    
    respond_to do |format|
      format.js
    end
  end

  def dynamic_devices
    @location = Location.find(params[:id])
    @devices = @location.get_devices
    
    respond_to do |format|
      format.js
    end
  end

  def sort_column
    PatientAssignment.column_names.include?(params[:sort]) ? params[:sort] : "monitor_end"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/patient_assignments_helper.rb
module PatientAssignmentsHelper
end

app/views/patient_assignments/_form.html.erb
<%= form_for(@patient_assignment) do |f| %>
  <% if @patient_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient_assignment.errors.count, "error") %> prohibited this Patient Assignment from being saved:</h2>

      <ul>
      <% @patient_assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="devices">
    <%= f.label :device_id, "Devices" %><br />
    <%= f.collection_select(:device_id, @devices, :id, :serial_number, :prompt => "Select a Device") %>
  </div>

  <div class="field" id="patients">
    <%= f.label :patient_id, "Patients" %><br />
    <%= f.collection_select(:patient_id, @patients, :id, :patient_full_name, :prompt => "Select a Patient") %>
  </div>

  <div class="field">
    <%= f.label :monitor_start %><br />
    <%= f.date_select :monitor_start %>
  </div>

  <div class="field">
    <%= f.label :monitor_end %><br />
    <%= f.date_select :monitor_end %>
  </div>

  <div class="field">
    <%= f.label :active, "Active" %>
    <%= f.check_box :active %>
  </div>
  <br />
  
  <div class="actions">
    <%= f.submit "Update Patient Assignment" %>
  </div>

<% end %>

app/views/patient_assignments/_form_archive.html.erb
<%= form_for(@patient_assignment) do |f| %>
  <% if @patient_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient_assignment.errors.count, "error") %> prohibited this Patient Assignment from being saved:</h2>

      <ul>
      <% @patient_assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<script type="text/javascript">
$(document).ready(function() {

  $("#patients").hide();
  $("#devices").hide();
  $("#_location_id").change(function() {

    var data=$('#_location_id').val();
    $.ajax({
      type: "POST",
       url: "http://"+location.host+"/dynamic_devices/"+data,
      data: data,

      beforeSend: function()
        {
        },

      success: function(response)
        {
          $("#patient_assignment_device_id").html(response);
          $("#devices").show();
        }
    });

    $.ajax({
      type: "POST",
       url: "http://"+location.host+"/dynamic_patients/"+data,
      data: data,

      beforeSend: function()
        {
        },

      success: function(response)
        {
          $("#patient_assignment_patient_id").html(response);
          $("#patients").show();
        }
    });
  });
});
</script>

  <div class="field">
    <%= f.label "Location" %><br />
    <%= collection_select(nil, :location_id, @locations, :id, :location_name, :prompt => "Select a Location") %>
  </div>

  <div class="field" id="devices">
    <%= f.label :device_id, "Devices" %><br />
    <%= f.collection_select(:device_id, @devices, :id, :serial_number, :prompt => "Select a Device") %>
  </div>

  <div class="field" id="patients">
    <%= f.label :patient_id, "Patients" %><br />
    <%= f.collection_select(:patient_id, @patients, :id, :patient_full_name, :prompt => "Select a Patient") %>
  </div>

  <div class="field">
    <%= f.label :monitor_start %><br />
    <%= f.date_select :monitor_start %>
  </div>

  <div class="field">
    <%= f.label :monitor_end %><br />
    <%= f.date_select :monitor_end %>
  </div>
  <br />
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/patient_assignments/dynamic_devices.js.erb
$('#patient_assignment_device_id').empty();
$('#patient_assignment_device_id').append('<option value="">Select a Device</option>')
<% for device in @devices %>
      $('#patient_assignment_device_id').append('<option value="<%= device.id %>"><%= device.serial_number %></option>')
<% end %>

app/views/patient_assignments/dynamic_patients.js.erb
$('#patient_assignment_patient_id').empty();
$('#patient_assignment_patient_id').append('<option value="">Select a Patient</option>')
<% for patient in @patients %>
      $('#patient_assignment_patient_id').append('<option value="<%= patient.id %>"><%= patient.patient_full_name %></option>')
<% end %>

app/views/patient_assignments/edit.html.erb
<h1>Editing Patient Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient_assignment %> |
<%= link_to 'Back', patient_assignments_path %>

app/views/patient_assignments/index.html.erb
<h1>Patient Assignments</h1>

<div align="center">
  <%= paginate @patient_assignments %>
</div>
<br />

<table class="pretty">
  <tr>
    <th>Patient</th>
    <th>Device Serial</th>
    <th><%= sortable "monitor_start", "Start Date" %></th>
    <th><%= sortable "monitor_end", "End Date" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patient_assignments.each do |patient_assignment| %>
  <tr class="<%= cycle('odd','even') %>">
    <td><%= patient_assignment.patient.last_name %>, <%= patient_assignment.patient.first_name %></td>
    <td><%= patient_assignment.device.serial_number %></td>
    <td><%= patient_assignment.monitor_start %></td>
    <td><%= patient_assignment.monitor_end %></td>
    <td><%= link_to 'Show', patient_assignment %></td>
    <td><%= link_to 'Edit', edit_patient_assignment_path(patient_assignment) %></td>
    <td><%= link_to 'Destroy', patient_assignment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />

<div align="center">
  <%= paginate @patient_assignments %>
</div>
<br />

<%= link_to 'New Patient assignment', new_patient_assignment_path %>

app/views/patient_assignments/new.html.erb
<h1>New Patient Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_assignments_path %>

app/views/patient_assignments/show.html.erb
<p>
  <b>Patient:</b>
  <%= @patient_assignment.patient.patient_full_name %>
</p>

<p>
  <b>Device:</b>
  <%= @patient_assignment.device.serial_number %>
</p>

<p>
  <b>Montior start:</b>
  <%= @patient_assignment.monitor_start %>
</p>

<p>
  <b>Monitor end:</b>
  <%= @patient_assignment.monitor_end %>
</p>


<%= link_to 'Edit', edit_patient_assignment_path(@patient_assignment) %> |
<%= link_to 'Back', patient_assignments_path %> |
<%= link_to 'New Patient', new_patient_path %> |
<%= link_to 'New Patient Assignment', new_patient_assignment_path %>