config/routes.rb
Inventory::Application.routes.draw do

#  devise_for :users
#  devise_scope :user do
#    get "signup",   :to => "accounts#new"
#    get "signin",   :to => "devise/sessions#new"
#    get "signout",  :to => "devise/sessions#destroy"
#  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  post "dynamic_devices/:id" => "patient_assignments#dynamic_devices", :as => "dynamic_devices"
  post "dynamic_patients/:id" => "patient_assignments#dynamic_patients", :as => "dynamic_patients"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "users/:id/password" => "users#password", :as => "reset_pass"
  get "reports/all_locations_summary" => "reports#all_locations_summary", :as => "all_locations_summary"
  get "reports/location_summary/:id" => "reports#location_summary", :as => "location_summary"
  get "reports/problematic_devices" => "reports#problematic_devices", :as => "problematic_devices"
  get "reports/devices_in_use" => "reports#devices_in_use", :as => "devices_in_use"
  get "device_by_location/:id" => "locations#devices_report", :as => "device_by_location"


  resources :device_batteries
  resources :device_carriers  
  resources :audits
  resources :disposable_types
  resources :disposables
  resources :devices
  resources :device_problem_statuses
  resources :device_problems
  resources :device_tests
  resources :device_types
  resources :device_statuses
  resources :groups
  resources :home
  resources :locations
  resources :location_assignments
  resources :location_types
  resources :patients
  resources :patient_assignments
  resources :practices
  resources :sessions
  resources :users do
    member do
      get 'password'
    end
  end


end

app/models/practice.rb
class Practice < ActiveRecord::Base
  validates :practice_name, :presence => true
  
  has_many :locations
  has_many :patients, :through => :locations
  has_many :devices, :through => :patients
  has_many :patient_assignments, :through => :patients
  
  accepts_nested_attributes_for :locations, :patients, :devices, :patient_assignments
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  load_and_authorize_resource

  # GET /practices
  # GET /practices.json
  def index
    @practices = Practice.order("practice_name").page(params[:page]).per(25)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @practices }
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    @practice = Practice.find(params[:id])
    @locations = @practice.locations
    @loc_count = 0

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @practice }
    end
  end

  # GET /practices/new
  # GET /practices/new.json
  def new
    @practice = Practice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @practice }
    end
  end

  # GET /practices/1/edit
  def edit
    @practice = Practice.find(params[:id])
    @locations = @practice.locations
    @loc_count = 0
  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(params[:practice])

    respond_to do |format|
      if @practice.save
        format.html { redirect_to @practice, notice: 'Practice was successfully created.' }
        format.json { render json: @practice, status: :created, location: @practice }
      else
        format.html { render action: "new" }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /practices/1
  # PUT /practices/1.json
  def update
    @practice = Practice.find(params[:id])

    respond_to do |format|
      if @practice.update_attributes(params[:practice])
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice = Practice.find(params[:id])
    @practice.destroy

    respond_to do |format|
      format.html { redirect_to practices_url }
      format.json { head :ok }
    end
  end

  def sort_column
    Practice.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_form.html.erb
<%= form_for(@practice) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :practice_name %><br />
    <%= f.text_field :practice_name %>
  </div>

  <%= f.fields_for :locations do |builder| %>
      <%= render :partial => "location_fields", :locals => { :f => builder, :loc_obj => @locations[@loc_count] } %>
      <% @loc_count = @loc_count + 1 %>
  <% end %>

  <% if can? :create, @location %>
    <p><%= link_to_add_association "Add Location", f, :locations %></p>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/practices/_location_alert_contact_fields.html.erb
<div class="nested-fields">
  <fieldset>
    <legend>Location</legend>
    <p>
      <%= f.label :user_id, "User" %><br />
      <%= f.collection_select(:user_id, User.all, :id, :user_full_name, :prompt => true) %>
    </p>
    <p>
      <%= link_to_remove_association "Remove Contact", f %>
    </p>
  </fieldset>
</div>

app/views/practices/_location_fields.html.erb
<div class="nested-fields">
  <fieldset>
    <legend>Location</legend>
    <p>
      <%= f.label :location_type_id %><br />
      <%= f.collection_select(:location_type_id, LocationType.all, :id, :location_type, :prompt => true) %>
    </p>
    <p>
      <%= f.label :location_name %><br />
      <%= f.text_field :location_name %>
    </p>
    <p>
      <%= f.label :location_street1 %><br />
      <%= f.text_field :location_street1 %>
    </p>
    <p>
      <%= f.label :location_street2 %><br />
      <%= f.text_field :location_street2 %>
    </p>
    <p>
      <%= f.label :location_city %><br />
      <%= f.text_field :location_city %>
    </p>
    <p>
      <%= f.label :location_state %><br />
      <%= f.text_field :location_state %>
    </p>
    <p>
      <%= f.label :location_zip %><br />
      <%= f.text_field :location_zip %>
    </p>
    <p>
      <%= f.label :location_contact %><br />
      <%= f.text_field :location_contact %>
    </p>
    <p>
      <%= f.label :par_level_scottcare %><br />
      <%= f.number_field :par_level_scottcare %>
    </p>
    <p>
      <%= f.label :par_level_mct %><br />
      <%= f.number_field :par_level_mct %>
    </p>
    <p>
      <%= f.label :par_level_event %><br />
      <%= f.number_field :par_level_event %>
    </p>
    <p>
      <%= f.label :alert_amount %><br />
      <%= f.number_field :alert_amount %>
    </p>
    <p>
      <%= f.label :active %><br />
      <%= f.check_box :active %>
    </p>

    <% f.fields_for :location_alert_contacts do |builder| %>
      <%= render :partial => "location_alert_contacts", :f => builder %>
    <% end %>

<%#= debug(loc_obj %>
%>
<%= debug(local_assigns[:loc_obj]) %>
    <p>
      <%= link_to_add_association "Add Contact", f, :location_alert_contacts %> | 
      <%= link_to_remove_association "Remove Location", f %> |
      <%#= link_to "Location Report", url_for(location_summary_path, id => local_assigns[:loc_obj].id) %> 
      %>
    </p>

  </fieldset>
</div>

app/views/practices/edit.html.erb
<h1>Editing practice</h1>

<%= render 'form' %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

app/views/practices/index.html.erb
<h1>Practices</h1>

<div align="center">
  <%= paginate @practices %>
</div>
<br />

<table class="pretty">
  <tr>
    <th>Practice name</th>
    <th></th>
    <% if can? :update, @practice %>
      <th></th>
    <% end %>
    <% if can? :destroy, @practice %>
      <th></th>
    <% end %>
  </tr>

<% @practices.each do |practice| %>
  <tr class="<%= cycle('odd','even') %>">
    <td><%= practice.practice_name %></td>
    <td><%= link_to 'Show', practice %></td>
    <% if can? :update, @practice %>
      <td><%= link_to 'Edit', edit_practice_path(practice) %></td>
    <% end %>
    <% if can? :destroy, @practice %>
      <td><%= link_to 'Destroy', practice, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>
<br />

<div align="center">
  <%= paginate @practices %>
</div>

<br />
<% if can? :create, @practice %>
  <%= link_to 'New Practice', new_practice_path %>
<% end %>

app/views/practices/new.html.erb
<h1>New practice</h1>

<%= render 'form' %>

<%= link_to 'Back', practices_path %>

app/views/practices/show.html.erb
<p>
  <b>Practice name:</b>
  <%= @practice.practice_name %>
</p>

<%= render @practice.locations %>

<% if can? :update, @practice %>
  <%= link_to 'Edit', edit_practice_path(@practice) %> |
<% end %>
<%= link_to 'Back', practices_path %>