config/routes.rb
Inventory::Application.routes.draw do

#  devise_for :users
#  devise_scope :user do
#    get "signup",   :to => "accounts#new"
#    get "signin",   :to => "devise/sessions#new"
#    get "signout",  :to => "devise/sessions#destroy"
#  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  post "dynamic_devices/:id" => "patient_assignments#dynamic_devices", :as => "dynamic_devices"
  post "dynamic_patients/:id" => "patient_assignments#dynamic_patients", :as => "dynamic_patients"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "users/:id/password" => "users#password", :as => "reset_pass"
  get "reports/all_locations_summary" => "reports#all_locations_summary", :as => "all_locations_summary"
  get "reports/location_summary/:id" => "reports#location_summary", :as => "location_summary"
  get "reports/problematic_devices" => "reports#problematic_devices", :as => "problematic_devices"
  get "reports/devices_in_use" => "reports#devices_in_use", :as => "devices_in_use"
  get "device_by_location/:id" => "locations#devices_report", :as => "device_by_location"


  resources :device_batteries
  resources :device_carriers  
  resources :audits
  resources :disposable_types
  resources :disposables
  resources :devices
  resources :device_problem_statuses
  resources :device_problems
  resources :device_tests
  resources :device_types
  resources :device_statuses
  resources :groups
  resources :home
  resources :locations
  resources :location_assignments
  resources :location_types
  resources :patients
  resources :patient_assignments
  resources :practices
  resources :sessions
  resources :users do
    member do
      get 'password'
    end
  end


end

app/controllers/location_types_controller.rb
class LocationTypesController < ApplicationController
  load_and_authorize_resource

  # GET /location_types
  # GET /location_types.json
  def index
    @location_types = LocationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @location_types }
    end
  end

  # GET /location_types/1
  # GET /location_types/1.json
  def show
    @location_type = LocationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location_type }
    end
  end

  # GET /location_types/new
  # GET /location_types/new.json
  def new
    @location_type = LocationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location_type }
    end
  end

  # GET /location_types/1/edit
  def edit
    @location_type = LocationType.find(params[:id])
  end

  # POST /location_types
  # POST /location_types.json
  def create
    @location_type = LocationType.new(params[:location_type])

    respond_to do |format|
      if @location_type.save
        format.html { redirect_to @location_type, notice: 'Location type was successfully created.' }
        format.json { render json: @location_type, status: :created, location: @location_type }
      else
        format.html { render action: "new" }
        format.json { render json: @location_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /location_types/1
  # PUT /location_types/1.json
  def update
    @location_type = LocationType.find(params[:id])

    respond_to do |format|
      if @location_type.update_attributes(params[:location_type])
        format.html { redirect_to @location_type, notice: 'Location type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location_types/1
  # DELETE /location_types/1.json
  def destroy
    @location_type = LocationType.find(params[:id])
    @location_type.destroy

    respond_to do |format|
      format.html { redirect_to location_types_url }
      format.json { head :ok }
    end
  end
end

app/helpers/location_types_helper.rb
module LocationTypesHelper
end

app/views/location_types/_form.html.erb
<%= form_for(@location_type) do |f| %>
  <% if @location_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location_type.errors.count, "error") %> prohibited this location_type from being saved:</h2>

      <ul>
      <% @location_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_type %><br />
    <%= f.text_field :location_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/location_types/edit.html.erb
<h1>Editing location_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @location_type %> |
<%= link_to 'Back', location_types_path %>

app/views/location_types/index.html.erb
<h1>Listing location_types</h1>

<table>
  <tr>
    <th>Location type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @location_types.each do |location_type| %>
  <tr>
    <td><%= location_type.location_type %></td>
    <td><%= link_to 'Show', location_type %></td>
    <td><%= link_to 'Edit', edit_location_type_path(location_type) %></td>
    <td><%= link_to 'Destroy', location_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location type', new_location_type_path %>

app/views/location_types/new.html.erb
<h1>New location_type</h1>

<%= render 'form' %>

<%= link_to 'Back', location_types_path %>

app/views/location_types/show.html.erb
<p>
  <b>Location type:</b>
  <%= @location_type.location_type %>
</p>


<%= link_to 'Edit', edit_location_type_path(@location_type) %> |
<%= link_to 'Back', location_types_path %>